apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: default
spec:
  selector:
    app: auth-service
  type: LoadBalancer
  ports:
    - name: http-auth
      port: 3000
      targetPort: 3000
      nodePort: 30000
      protocol: TCP
    - name: http-tcp-port
      port: 3001
      targetPort: 3001
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: default
spec:
  selector:
    app: users-service
  type: LoadBalancer
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      protocol: TCP
    - name: new-port
      port: 4001
      targetPort: 4001
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
